apiVersion: v1
kind: Pod
metadata:
  name: customer-service-db
  labels:
    app: customer-service-db
    tier: api
spec:
  containers:
    - name: customer-service-db
      image: localhost/customerdb:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password123
      ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: customer-service
  labels:
    app: customer-service
    tier: api
spec:
  containers:
    - name: customer-service
      image: localhost/customer-service:0.0.1-SNAPSHOT