apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'customer-service'
        static_configs:
          - targets: ['192.168.0.100:8081']
        metrics_path: 'actuator/prometheus'
