FROM openjdk:8-jdk-alpine
ENV APP_FILE customer-service-0.0.1-SNAPSHOT.war
ENV APP_HOME /app
EXPOSE 8081:8081
COPY target/$APP_FILE $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]